Package: std-msgs
Version: 0.1.0
Section: misc
Priority: extra
Architecture: any
Depends: python-empy, cmake
Build-Depends: cmake, python, python-empy, python-setuptools,
               @(PackagePrefix)catkin, @(PackagePrefix)genmsg,
               @(PackagePrefix)gencpp, @(PackagePrefix)genpy, @(PackagePrefix)genpybindings
Description: Standard ROS Message
Author: The ROS Ecosystem
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org
Catkin-DebRulesType: cmake
Catkin-CopyrightType:  willowgarage
Catkin-Depends: catkin, genmsg, genpybindings
Catkin-ProjectName: std_msgs

